package com.saha.amit.soapclient.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;
import org.springframework.boot.webservices.client.WebServiceTemplateBuilder;
import org.springframework.ws.client.core.WebServiceTemplate;

@Configuration
public class SoapClientConfig {

  @Value("${soap.server.url:http://localhost:8080/ws}")
  private String serverUrl;

  @Bean
  public Jaxb2Marshaller marshaller() {
    Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
    // Package generated by XJC from employee.xsd
    marshaller.setContextPath("com.saha.amit.employee");
    return marshaller;
  }

  @Bean
  public WebServiceTemplate webServiceTemplate(WebServiceTemplateBuilder builder, Jaxb2Marshaller marshaller) {
    return builder
        .setDefaultUri(serverUrl)
        .setMarshaller(marshaller)
        .setUnmarshaller(marshaller)
        .build();
  }
}
