apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: infra
data:
  init.sql: |
    -- postgres
    -- Create the schema if it doesn't exist
    CREATE SCHEMA IF NOT EXISTS microservice;

    -- Create the table inside the schema
    CREATE TABLE IF NOT EXISTS microservice.customers (
        id              BIGSERIAL PRIMARY KEY,
        name            VARCHAR(255) NOT NULL,
        email           VARCHAR(255) NOT NULL,
        created_at      BIGINT NOT NULL,
        password_salt   VARCHAR(255) NOT NULL,
        password_hash   VARCHAR(255) NOT NULL,
        CONSTRAINT uq_customers_email UNIQUE (email)
        );

    -- Create the index inside the schema
    CREATE INDEX IF NOT EXISTS idx_customers_created_at ON microservice.customers (created_at);


    CREATE TABLE IF NOT EXISTS microservice.orders (
        order_id CHAR(36) NOT NULL PRIMARY KEY,
        customer_id VARCHAR(36) NOT NULL,
        amount DECIMAL(10,2) NOT NULL,
        status VARCHAR(20) NOT NULL,
        created_at BIGINT NOT NULL
        );

    CREATE TABLE IF NOT EXISTS microservice.order_outbox (
        id CHAR(36) NOT NULL PRIMARY KEY,
        aggregate_id CHAR(36) NOT NULL,
        event_type VARCHAR(100) NOT NULL,
        payload TEXT NOT NULL,
        status VARCHAR(20) NOT NULL,
        created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        last_error TEXT NULL,
        attempts INT NOT NULL DEFAULT 0
        );

    CREATE INDEX IF NOT EXISTS idx_order_outbox_status_available
        ON microservice.order_outbox (status, available_at);
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "dbadmin"
            - name: POSTGRES_PASSWORD
              value: "dbpassword"
            - name: POSTGRES_DB
              value: "customerdb"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
